Algoritmo "Campo Minado"
//
//
// Descrição   : Jogo Campo minado
// Autor(a)    : André Vitor e Kauê Batista
// Data atual  : 09/03/2023
Var
// Seção de Declarações das variáveis
mat: vetor [1..9, 1..9] de inteiro
linha: inteiro
co: inteiro

i: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

para i <- 1 até 66 faca
escreva("Indique a linha: ")
leia(linha)
escreva("Indique a coluna: ")
leia(co)




Fimalgoritmo
