Algoritmo "Campo Minado"
// 
//  
// Descrição   : Jogo Campo minado
// Autor(a)    : André Vitor e Kauê Batista
// Data atual  : 09/03/2023
Var
// Seção de Declarações das variáveis 
inteiro mat[9][9] = {{10,1,2,1,0,0,0,1,1}
                     {10,2,10,2,0,0,1,2,10}
                     {10,4,10,2,0,0,2,10,2}
                     {






Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo